### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by FotieMConstant** [Idered/chalk.ist#10]
Feature: Would love a few more background options, maybe some kind of gradient selection or image selection would be amazing!
User: [Anthony Young](https://www.producthunt.com/@anthony_young3)

**Comment by mfurquim** [comment]
Hi 👋🏾 

I'm not entirely sure if this is the place, but I just added a theme inspired by [Nord](https://www.nordtheme.com/) on my fork.
Would you guys be interested in merging it?

I can create a Pull Request if so.

**Comment by Idered** [comment]
@mfurquim looks great! Please open PR, thanks
