### ISSUE TITLE
Improve Windows Control UI

### ISSUE THREAD

**Issue by stanleyowen** [Idered/chalk.ist#16]
chalk.ist is an awesome projects! Everything is well-designed, and I notice it would be great to improve the windows control UI to a more colorful button into something like this:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/69080584/167325970-777774c6-96f2-4162-9c09-92d38f8abd88.png">

**Comment by kimlimjustin** [comment]
May I fix this?

**Comment by FotieMConstant** [comment]
This looks great 👍🏾
