### ISSUE TITLE
[Bug] Download MP4 does not work on Firefox

### ISSUE THREAD

**Issue by chand1012** [Idered/chalk.ist#28]
Here is the console error message.

![image](https://github.com/Idered/chalk.ist/assets/3521582/885464f7-a67e-4592-b11c-831f244d9399)

Firefox may just have to be dropped from the supported list of MP4 download browsers, as according to MDN, [Firefox doesn't support the encoder](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder).

**Comment by Idered** [comment]
Thanks for report, I've hidden that option on firefox(broken) and safari(super slow)
