### ISSUE TITLE
Typescript Regex does not get highlighted

### ISSUE THREAD

**Issue by OmkarK45** [Idered/chalk.ist#4]
Hey! This project is really awesome. I found a small bug where regex string is not highlighted by theme 
![image](https://user-images.githubusercontent.com/45557594/162984861-9265a88c-d669-4a38-92c9-eb139b4e84af.png)

**Comment by Idered** [comment]
@OmkarK45 Thanks! Fixed it with https://github.com/Idered/chalk.ist/commit/fbc2e1a20959fcae97ce2f1e842b800406f45a74
