### ISSUE TITLE
Was there a diff mode or I was dreaming?

### ISSUE THREAD

**Issue by vandriesh** [Idered/chalk.ist#40]
it's not that easier with new (manual) add/remove markers .

But let me know if I was dreaming... 

Cool service btw, 

Keep up the good job!

**Comment by Idered** [comment]
Yup, there was a diff mode based on the Monaco editor, which I removed because it weighed a ton. The current solution can be improved by adding click-and-drag functionality to select multiple items but I don't have time to work on that now

**Comment by Idered** [comment]
Yup, thanks to vercel there's this build https://chalk-m5fmotbhu-alto.vercel.app/
