### ISSUE TITLE
an emoji can break the window title

### ISSUE THREAD

**Issue by danielroe** [Idered/chalk.ist#51]
using an emoji in the title of the window seems to cause it to jump down a line, but only when rendering:

![image](https://github.com/user-attachments/assets/789e8b2c-35f6-4cef-aa4c-2a274c5b70a8)
![CleanShot 2024-10-12 at 00 16 29@2x](https://github.com/user-attachments/assets/f3b35768-b03b-49f8-be5b-25736c21fa61)

**Comment by Idered** [comment]
Fixed 🍻

**Comment by danielroe** [comment]
🔥
