### ISSUE TITLE
<textarea> handles input incorrectly.

### ISSUE THREAD

**Issue by StellarSt0rm** [Idered/chalk.ist#64]
# Issue
The `<textarea>` (`.editor` class) handles user input incorrectly (Not *really*, but it's very infuriating), all input is joined into one line, making editing the text hard. The exact problem is newlines not being actually shown.

# Similar issue exists?
No, i checked if anyone had reported it, but no one has.

# Fix
Adding `white-space: pre-wrap` CSS rule to the `.editor` class works, not sure if there's other ways to fix it, or if this one is the best.

# Videos for demonstration
Without the fix:
[Screencast from 12-10-2024 10:38:30 PM.webm](https://github.com/user-attachments/assets/034144ff-61fe-46c8-ae64-3ca99ecf7d6b)

With the fix:
[Screencast from 12-10-2024 10:39:24 PM.webm](https://github.com/user-attachments/assets/a3eef8ba-d0d1-4525-b0da-ead69afb6f96)

# Browser
Firefox 133.0 (Zen 1.0.2-b.0) 64-bit

**Comment by Idered** [comment]
Hey @StellarSt0rm, thanks for report! I've pushed a fix
